# Generated by Django 3.2.4 on 2021-06-25 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsRequest',
            fields=[
                ('page', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'ordering': ['team'],
            },
        ),
        migrations.CreateModel(
            name='PlayersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('totalPages', models.IntegerField()),
                ('totalResults', models.IntegerField()),
                ('commonName', models.CharField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(blank=True, max_length=10, null=True)),
                ('nation', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_players.teamsrequest')),
            ],
            options={
                'verbose_name_plural': 'juagadores',
                'ordering': ['commonName'],
            },
        ),
    ]
